export const GET_MEMBERS_START = 'GET_MEMBERS_START';
export const GET_MEMBERS_SUCCEED = 'GET_MEMBERS_SUCCEED';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';
export const CREATE_MEMBER_START = 'CREATE_MEMBER_START';
export const CREATE_MEMBER_SUCCEED = 'CREATE_MEMBER_SUCCEED';
export const CREATE_MEMBER_FAIL = 'CREATE_MEMBER_FAIL';
export const DELETE_MEMBER_START = 'DELETE_MEMBER_START';
export const DELETE_MEMBER_SUCCEED = 'DELETE_MEMBER_SUCCEED';
export const DELETE_MEMBER_FAIL = 'DELETE_MEMBER_FAIL';

export const CALL_START = 'CALL_START';
export const CALL_SUCCEED = 'CALL_SUCCEED';
export const CALL_FAIL = 'CALL_FAIL';
